name: Automatic tests and code-coverage
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.x'
      - name: Run unit tests and code-coverage
        run: |
          go test -covermode=atomic ./...